### ISSUE TITLE
issue_comment and issue.html_url

### ISSUE THREAD

**Issue by dontcallmedom** [darobin/github-hook-simplify#1]
https://github.com/w3c/midgard tries to display a link to the original issue when treating an `issue_comment`, but this library specifically reduces the `issue` object for `issue_comment` to just the number, and thus removes the `html_url` property.

I'm happy to provide a patch to change this behavior, but I'm not clear on what the reasoning behind special-casing `issue_comment` is in the first pace.

**Comment by darobin** [comment]
`issue_comment` isn't special-cased, it's just one of the things that this library simplifies.

The problem it solves is that hooks contain a lot of information, and we'd like to avoid storing too much duplicate content. Also, a lot of that information is denormalised (e.g. if you rename the issue, it won't be renamed in `issue_comment.issue` if you've stored it a while). Simplification helps with that.

Can't you reconstruct the `html_url` with `https://github.com/${full_name}/issues/${issue}`?

**Comment by dontcallmedom** [comment]
well, it is special-cased (there is an if (event === "issue_comment") in the code), but anyway, if there are good reasons not to keep that info around, I'll do it with reconstructing. It just seemed a pity to undo the undoing :)

**Comment by darobin** [comment]
Oh, I think that's just because other events types might need to keep the issue data around (notably issue creation) but unlike in the rest of the code they can't be distinguished on the data alone. It's not really a special-case, more of a coincidence I would say.
